# to run: docker-compose run
#
# Create a .env file in the same folder as this file and change the variables.
# MOUNT_POINT=/tmp/
# VPN_PROVIDER=changeme
# VPN_CONFIG=changeme
# VPN_USERNAME=changeme
# VPN_PASSWORD=changeme
#
#
version: "2"

services:
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
    networks:
      - plexnet
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
    environment:
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_CONFIG=${VPN_CONFIG}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=10.0.0.0/16
    volumes:
      - ${MOUNT_POINT}/transmission:/data
      - /etc/localtime:/etc/localtime:ro
  proxy:
    image: haugene/transmission-openvpn-proxy
    networks:
      - plexnet
    links:
      - transmission
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
      - ${MOUNT_POINT}/radarr-config:/config
      - ${MOUNT_POINT}/transmission/completed:/downloads
      - ${MOUNT_POINT}/plex/movies:/movies
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
      - ${MOUNT_POINT}/sonarr/config:/config
      - ${MOUNT_POINT}/plex/tv:/tv
      - ${MOUNT_POINT}/transmission/completed:/downloads
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
      - ${MOUNT_POINT}/jackett/config:/config
    ports:
      - "9117:9117"
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: always
    ports:
      - "32400:32400"
      - "1900:1900"
      - "3005:3005"
      - "5353:5353"
      - "8324:8324"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"
      - "32469:32469"
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
      - ADVERTISE_IP=http://10.0.0.31:32400/
      - PLEX_CLAIM=claim-b9pAgVomLHcjnssBF6sy
    volumes:
      - ${MOUNT_POINT}/plex-config:/config
      - ${MOUNT_POINT}/plex:/data
      - /tmp/plex-transcode:/transcode
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    restart: always
    ports:
            - "8686:8686"
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
      - ${MOUNT_POINT}/lidarr-config:/config
      - ${MOUNT_POINT}/transmission/completed:/downloads
      - ${MOUNT_POINT}/plex/music:/music
networks:
  plexnet:
    ipam:
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
